### ISSUE TITLE
Updating Play Services gradle version

### ISSUE THREAD

**Issue by OoredooMobile** [dimelo/Dimelo-Android#11]
Can you please use the latest `play-services-gcm` version.

it keeps getting errors and conflict with the App gradle newest version

**Comment by Cylix** [comment]
Hi,

Interestingly, we were planning to bump the version of play services in the SDK and it was just waiting to be merged.

I just deployed it in version 1.4.2.

Can you confirm me that this solves your issue?

Best

**Comment by OoredooMobile** [comment]
yes you can, sorry i forgot to get back to you.

Thank you

PS: google service version now is 10.0.1

**Comment by Cylix** [comment]
Thank you for getting back to me.
Indeed, a new version has been released in the meantime: we will check that whenever we can.
