### ISSUE TITLE
Resource string id "app_name" conflicts

### ISSUE THREAD

**Issue by pedrocactus** [dimelo/Dimelo-Android#13]
Hello,

Resource string id "app_name" is used in values-fr and values. As almost every app has this string id by default to name their app. It is not a big issue but if you don't have any resources in values-fr, your app will be named "Live Chat" in a french config device. Might be handful to change this id on your side than let the client do it.

Cheers

**Comment by Cylix** [comment]
Hi,

Thanks for reporting that, I'll submit a change.

Best

**Comment by Cylix** [comment]
We provided translation for the app_name.
It has been released under v1.5.0.

**Comment by pedrocactus** [comment]
I did not mentioned the translation, i said that you should not provide a string resource with "app_name" as a key. It's useless and make the clients implement their app name with another string resource key. In other words, with your new version,  we have to create a special values-fr with a key "app_name" to override yours

**Comment by Cylix** [comment]
Ok my bad, we completely misunderstood ourselves. Will check for a future release then, thanks for your feedback.

**Comment by chawax** [comment]
Has this been fixed ? We use Dimelo SDK in our app and the name of the app is "Live chat" (the Dimelo one) instead of our app name.

**Comment by jarthod** [comment]
@chawax it seems a fix was issued but later reverted, I'm investigating this
