### ISSUE TITLE
Send button colors inverted

### ISSUE THREAD

**Issue by pedrocactus** [dimelo/Dimelo-Android#14]
Hello,
I am using v1.4.3
The send button has by default two colors for enabled( very light grey) and disabled( black).
Those colors seems to be inverted as grey should be the disabled color and black the enabled one.
Anyway, we can change the send button disabled color with: `customization. setSendButtonDisabledColor(int color)`
but unfortunately there is no equivalent for the enabled color.

Cheers

**Comment by Cylix** [comment]
Hi,

Indeed, the colors seem confusing at first, I'll make the update.

However, you should be able to customize the disabled button using the [existing customization property](https://github.com/dimelo/Dimelo-Android/blob/master/ChatCustomization.md#send-button-disabled-color).
This option is technically available starting from v1.1.2.

I just tested it using the XML attribute and it worked on my SampleApp.

Could you confirm me that this customization attribute solves your issue?

Best

**Comment by pedrocactus** [comment]
yes you can change the disabled color for the send button. But not for the enabled color, which is by default a very light grey. I updated my first comment

**Comment by Cylix** [comment]
I worked yesterday on this issue and simply add a setSendButtonEnabledColor. I also changed the default disabled color to grey.

I'll notify you here once it will be released.

**Comment by Cylix** [comment]
The changes just have been released in the v1.5.0.

**Comment by pedrocactus** [comment]
thx for the new method !! Default color values are still inverted though

**Comment by Cylix** [comment]
Thanks for the feedback.
Concerning the default color of the send button, can you provide me some screenshots of what you get?
On my side, I now have the appropriate colors:
![capture d ecran 2017-01-18 a 15 30 35](https://cloud.githubusercontent.com/assets/3252462/22067857/3f0797aa-dd93-11e6-81e3-400379f0f965.png)
![capture d ecran 2017-01-18 a 15 30 24](https://cloud.githubusercontent.com/assets/3252462/22067856/3f05fc56-dd93-11e6-9bdb-71f964e444ed.png)

For your information, the enable color by default uses your main theme primary color, which might be light grey on your side?
