### ISSUE TITLE
When the Detroy method is called in Chat.java, a nullpointerException appears with version 1.5.2

### ISSUE THREAD

**Issue by jfgrim** [dimelo/Dimelo-Android#18]
I have a NullpointerException when the destroy method id called :

 **Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.setAdapter(android.support.v7.widget.RecyclerView$Adapter)' on a null object reference at com.dimelo.dimelosdk.main.Chat.onDestroyView(Chat.java:1479)**

In onDestroyView() in Chat.java, you do this : 
        this.mGalleryRecyclerView.setAdapter((Adapter)null);

But if you don't use GalleryRecyclerView, this object remains at Null. And when i pressing back button, the crash appears.

**Comment by Cylix** [comment]
Hi,

Thanks for reporting the issue, that's a good catch!
I pushed a fix in v1.5.3.

Best,
