### ISSUE TITLE
Date format Android

### ISSUE THREAD

**Issue by maresc-g** [dimelo/Dimelo-Android#2]
Hi,

It is possible with the iOS SDK to set a custom date formatter. However, I didn't find anything to do it with the Android SDK.
Is it possible ? If not, will it be added in a new release ?

Thanks

**Comment by elhu** [comment]
Hi,

For now, the Android SDK displays the date according to the device's locale.
There is currently no plan to allow a custom date formatter, but that's something we could consider.

**Comment by maresc-g** [comment]
Ok, thanks for the information.
