### ISSUE TITLE
Photo from camera is not attached

### ISSUE THREAD

**Issue by ghost** [dimelo/Dimelo-Android#20]
I can't attach photo from camera.
I open the chat, open the camera from attach panel, do photo and click the button to attach. Then the chat opens without any attachment, and galery is not updated.

**Comment by jarthod** [comment]
Hi, could you please share some screenshots of the different screens you get and where you tap between each?

**Comment by ghost** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/8168379/26546067/5e2baf3e-4492-11e7-8b26-1bd4e4536275.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/8168379/26546068/5e33a6f8-4492-11e7-80ce-7b832cdde869.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/8168379/26546070/5e4dcf6a-4492-11e7-9cbe-6f55533f5c44.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/8168379/26546071/5e540ef2-4492-11e7-80ff-c7770c191ba9.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/8168379/26546072/5e60fb62-4492-11e7-8f2c-97c5f832e974.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/8168379/26546073/5e615da0-4492-11e7-8bac-97a5cf3c086d.png)

**Comment by jarthod** [comment]
Ok thanks a lot for the screens, we'll have a look into this.
Does it work if you upload from the gallery instead of the camera?

Also, could you try with the latest version of the SDK (1.5.3) ?
We fixed a few things related to camera and gallery in between which may be related.

**Comment by ghost** [comment]
Yes, it works with the gallery.
With version 1.5.3 nothing changed.

**Comment by jarthod** [comment]
Ok thank you. Could please give me in addition:
- Your device and Android version
- Do you have this issue on several devices / emulators / android versions?
- The first 6 chars of your public API key

**Comment by ghost** [comment]
Sorry for delayed response.
I have this issue on any device (e.g. Motorola Moto G XT1541 8Gb  Android 6.0).
On Google Pixel Phone / Nexus S1 with Android 7.1.1 (Nougat) I have a crash (logs in attachment).
The first 6 chars of public API key "c3c374".
[log.txt](https://github.com/dimelo/Dimelo-Android/files/1080854/log.txt)

**Comment by jarthod** [comment]
Thanks, we're having a look

**Comment by amalcev** [comment]
Hi, do you have a solution for this issue?

**Comment by jarthod** [comment]
Hi, sorry for the delay but we're currently working on this.
I guess you're having the same issue @amalcev? If so and you're not working with @IlyaTolstihin would you mind sharing your crash log too?

**Comment by amalcev** [comment]
I am working together with @IlyaTolstihin. So nothing new to add.

**Comment by jarthod** [comment]
@IlyaTolstihin @amalcev we've managed to fix this issue, it's currently under code review and will be in the next release. Thank you for your patience. :relieved:

**Comment by jarthod** [comment]
The fix for this bug has been released in `1.6.0`, please give this version a try a report any issue you still have. Sorry for the wait!
