### ISSUE TITLE
Crash when displaying messages with attached photo

### ISSUE THREAD

**Issue by ghost** [dimelo/Dimelo-Android#24]
Hello,
We have a new crash and seems it doesn't depend on sdk version (We have the issue with 1.5.3 and 1.6.0) . Logs in attachment.

[log.txt](https://github.com/dimelo/Dimelo-Android/files/1172927/log.txt)

**Comment by jarthod** [comment]
Hello, Thanks for this report, we just release a patch version (`1.6.1`) with a fix for this exception, could you please update and let us know if you have any other issue.
