### ISSUE TITLE
Google Play Services version

### ISSUE THREAD

**Issue by openkwaky** [dimelo/Dimelo-Android#25]
Hello,

I have a conflict warning in my App gradle file because you are using version 10.0.1 instead of last version 11.0.2, cf https://developers.google.com/android/guides/setup
If there is no impact for dimelo lib, can you update your dependency please ?

**Comment by jarthod** [comment]
Hello,

GPS has been upgraded to `11.0.4` in the latest release of our SDK (`1.6.2`)
Please give it a try.
