### ISSUE TITLE
Chat can not attach photo directly from camera

### ISSUE THREAD

**Issue by thedrugsthatdeceiveyou** [dimelo/Dimelo-Android#26]
This issue can be related to https://github.com/dimelo/Dimelo-Android/issues/20

Steps to reproduce:
1. Open chat
2. Tap the attachment icon, then tap on photo icon
3. Take a photo, tap the OK narrow
Issue: photo was not attached, gallery sheet doesn't  display the recent photo.  Close attachment bar, then open it again – new photo is displayed.

**Comment by jarthod** [comment]
Which version of Android and the SDK are you running?
Do you have an exception or something?

**Comment by thedrugsthatdeceiveyou** [comment]
This reproduces on Android versions from 4.4 to 7 (we do not use lower versions)
The SDK version is 1.6.1
We don't have any exception

**Comment by waelba** [comment]
Do you have the camera permission in your manifest ?

```   
<uses-permission android:name="android.permission.CAMERA" />
```

**Comment by thedrugsthatdeceiveyou** [comment]
Yes, we have permission in manifest

**Comment by jarthod** [comment]
Hello, we've released a fix about camera detection in `1.6.2`, could you please try this version and let us know if you still have this problem.

**Comment by thedrugsthatdeceiveyou** [comment]
We still have this problem. You can see it on the video here https://drive.google.com/drive/folders/0B8iNIlKALd51Y090cmVaNEZlYzQ

**Comment by jarthod** [comment]
Ok, thank you very much for the video, we're investigating :)

**Comment by waelba** [comment]
@thedrugsthatdeceiveyou  did you call  mDimeloChat.onActivityResult(requestCode, resultCode, data) inside the function onActivityResult in your parent Activity or fragment ?

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        // DimeloChat is a nested Fragment, we must notify it about onActivityResult
        mDimeloChat.onActivityResult(requestCode, resultCode, data);
    }

**Comment by thedrugsthatdeceiveyou** [comment]
Now it works, thanx!

**Comment by jarthod** [comment]
Great !
