### ISSUE TITLE
Crash on setApiSecret

### ISSUE THREAD

**Issue by JcaDroid** [dimelo/Dimelo-Android#27]
Hello,

I'm facing a crash when calling setApiSecret : 
Fatal Exception: java.lang.NullPointerExceptionAttempt to invoke virtual method 'com.dimelo.dimelosdk.Models.UserDatas com.dimelo.dimelosdk.main.DataManager.getUserDatas()' on a null object reference

Here is the code : 
```
Dimelo.setup(context);
Dimelo dimelo = Dimelo.getInstance();
dimelo.setApiSecret(secret);
```
And secret is not null.

Can you help me ?

**Comment by waelba** [comment]
Hello @JcaDroid ,
Could you please let me know which version of the SDK you're using?
