### ISSUE TITLE
Map location is not attached

### ISSUE THREAD

**Issue by thedrugsthatdeceiveyou** [dimelo/Dimelo-Android#28]
Steps to reproduce:
1. Open chat
2. Tap the attachment icon, then tap on map picker icon
3. Choose the location, tap "Sélectionner cette position", then tap "Sélectionner"
4. Tap the OK narrow
Issue: location is not attached

This reproduces on Android versions from 4.4 to 7 (we do not use lower versions)
The SDK version is 1.6.1

**Comment by jarthod** [comment]
Did you set a Google Map API key? (https://github.com/dimelo/Dimelo-Android#activate-location-messages) and if so could you please send it to Dimelo through a private channel?

**Comment by thedrugsthatdeceiveyou** [comment]
Could you pls describe how can I send the Key to Dimelo through a private channel?

**Comment by jarthod** [comment]
You can send it to `support@dimelo.com` with a mention to this ticket.

**Comment by thedrugsthatdeceiveyou** [comment]
The key was sent to support@dimelo.com

**Comment by jarthod** [comment]
This key seem to work in debug but not in release mode, did you generate it using the release keystore?

**Comment by thedrugsthatdeceiveyou** [comment]
Could you explain which modes are you talking about?

**Comment by waelba** [comment]
To generate the map key you used a debug keystore(debug.keystore) or release keystore (your own keystore). For debug it works by cons resease it does not work.

Release
![release](https://user-images.githubusercontent.com/6080628/29071559-75af4a50-7c44-11e7-9018-08d8ffc86a9d.png)

Debug
![debug](https://user-images.githubusercontent.com/6080628/29071560-75e9e55c-7c44-11e7-9f52-094391fbd4e4.png)

**Comment by thedrugsthatdeceiveyou** [comment]
Api Key was correct. The problem was with call mDimeloChat.onActivityResult(requestCode, resultCode, data) inside the function onActivityResult in our parent fragment, we added this and now all works

**Comment by jarthod** [comment]
Makes sense, ok I'm closing this then.
