### ISSUE TITLE
No pushes received

### ISSUE THREAD

**Issue by thedrugsthatdeceiveyou** [dimelo/Dimelo-Android#29]
I initialize Dimelo using the methods Dimelo.setup() and Dimelo.setApiKey().
After that I set device token and user identifier, but I can't receive any pushes until I open the chat and close it.

SDK version is 1.6.1

**Comment by jarthod** [comment]
I'm not sure what you mean, after you open the chat and close it, the push notifications works? if you close the app too? when do they stop working exactly?

**Comment by thedrugsthatdeceiveyou** [comment]
Push notifications don't work if the app is in background or closed

**Comment by jarthod** [comment]
But they do work when the app is open? how do you know this?
Is you APNs cert properly setup on Dimelo Digital side?

**Comment by thedrugsthatdeceiveyou** [comment]
On Sony F5321 (Android 6.0.1) pushes are received only when app is in foreground. 
On Samsung Galaxy S7 (Android 7.0) pushes are received after user opened the chat first time, both on foreground and background

**Comment by jarthod** [comment]
Ok thanks, we'll run some tests and get back to you.

**Comment by amalcev** [comment]
Hi, do you have any news on this point?

**Comment by DrissTM** [comment]
Hi, can you try to upgrade your Dimelo Mobile SDK version to 1.6.2 ? 
We deployed a change that make notifications more permissive.

**Comment by thedrugsthatdeceiveyou** [comment]
Pushes on SDK version 1.6.2 work well, thanks
