### ISSUE TITLE
No method called sendMessage

### ISSUE THREAD

**Issue by karimkod** [dimelo/Dimelo-Android#32]
Hello, 

When reading the doc of the sdk I found a method called sendMessage that takes a string as a param, it allows us to send a message programaticaly but when working I can't find it it's on the Dimelo class. 

Thanks for answering. 
Greetings

**Comment by jarthod** [comment]
Hello,

This method was added in the `1.6.4` version, what is the version you're using?

**Comment by karimkod** [comment]
Hi agian, thanks for answering, actually I cloned the github project, I think I updated it ot 1.4.4.
I'll go up to 1.6.4 and give you feed back.

**Comment by jarthod** [comment]
Ok, should be better indeed ;)
