### ISSUE TITLE
Unread messages counter is not received until push

### ISSUE THREAD

**Issue by thedrugsthatdeceiveyou** [dimelo/Dimelo-Android#34]
I execute the following steps
1) dimelo.setUserIdentifier(identifier);
dimelo.setUserName(name);
dimelo.setAuthenticationInfo(authInfo);
2) Obtain jwt and set it.
Dimelo.getInstance().setJwt(jwt);
3) Then I try to fetch unread count and set listener, but these callbacks don't trigger until I receive push notification.
Dimelo.getInstance().fetchUnreadCount()
Dimelo.getInstance().setUnreadCountChangedListener()

**Comment by DrissTM** [comment]
Hi !

We're taking a look at this issue and will get back to you ASAP

**Comment by DrissTM** [comment]
It is the normal behavior, we only update the unread message count (execute the callbacks) when we receive a new message (so when you receive a notification).

If you need to get the current unread message count without receiving a notification you can use:
`Dimelo.getInstance().getUnreadCount()`

**Comment by thedrugsthatdeceiveyou** [comment]
I tried to use this method, but it returnes 0

**Comment by DrissTM** [comment]
Did the chat has been displayed in the mean time ?
This function will always return 0 if you call it from the chat view as it reset the unread message counter

**Comment by thedrugsthatdeceiveyou** [comment]
No, the chat was not displayed since the app was opened

**Comment by DrissTM** [comment]
Hi @thedrugsthatdeceiveyou !

Maybe the counter didn't have the time to synchronize when it was called, you can force its updating by using this:

```
Dimelo.getInstance().fetchUnreadCount(new Dimelo.UnreadCountCallback() {
    @Override
    public void onSuccess(final int i) {
        Log.e("count", Dimelo.getInstance().getUnreadCount() + "");
    }
    
    @Override
    public void onError(DimeloConnection.DimeloError dimeloError) {
        
    }
});
```

Let me know if it solved your problem ;)

**Comment by thedrugsthatdeceiveyou** [comment]
Unfortunately, this didn't help. With this method the counter is not received at all

**Comment by DrissTM** [comment]
Can you give me a snippet of the code you're running ?

And is the Dimelo instance initialized with the right informations (userIdentifier, username, ...) at the moment you run this function ?

**Comment by thedrugsthatdeceiveyou** [comment]
final Dimelo dimelo = Dimelo.getInstance();
final String userIdentifier = dimelo.getUserIdentifier();
final String userName= dimelo.getUserName();
final String jwt = dimelo.getJwt();
// userIdentifier == ***
// userName == ***
// jwt == null
dimelo.fetchUnreadCount(new Dimelo.UnreadCountCallback() {
@Override
public void onSuccess(final int i) {
   unreadDimeloSubject.onNext(i);
}

@Override
public void onError(final DimeloConnection.DimeloError dimeloError) {

   }
});
dimelo.setUnreadCountChangedListener(unreadDimeloSubject::onNext);
unreadDimeloSubject.onNext(dimelo.getUnreadCount());

**Comment by DrissTM** [comment]
Are you initializing the SDK with an API secret before calling this code ?

**Comment by thedrugsthatdeceiveyou** [comment]
We use API key and yes, before calling this code

**Comment by jarthod** [comment]
What do you mean by "the counter in not received" ? the fetch method needs 2 callbacks for success and error, one of them must be called. Also if there is an error you should see a message in your logs, please let us know which callback is called and with what value.

**Comment by thedrugsthatdeceiveyou** [comment]
None of two callbacks is called until we receive push notification.

**Comment by waelba** [comment]
For Push notification you made the call to  `Dimelo.consumeReceivedRemoteNotification()` from your Service?

**Comment by thedrugsthatdeceiveyou** [comment]
Yes
`Dimelo.consumeReceivedRemoteNotification(this, extras, new DimeloNotificationDisplayer())`

**Comment by waelba** [comment]
so you can extarct the number of unread message directly from the notification 

 ```
String appdata =  extras.get("appdata").toString();
try {
     JSONObject obj = new JSONObject(appdata);                     
     Log.e("badgeCount", obj.getInt("n"));
 } catch (Throwable t) {}
```

**Comment by thedrugsthatdeceiveyou** [comment]
The issue is we cannot initially receive unread count without receiving push notification

**Comment by waelba** [comment]
Did you do the Dimelo initialization with the first method (apiSecret) or with the second method(apiKey + JWT) ?
Can you give me a snippet of the Dimelo initialization code. Thx

**Comment by thedrugsthatdeceiveyou** [comment]
1)setup Dimelo
public class App extends Application {

   @Override
   public void onCreate() {
       if (A4S.isInA4SProcess(this)) {
           return;
       }
       super.onCreate();
       Dimelo.setup(this);
       Dimelo.getInstance().setApiKey(BuildConfig.DIMELO_API_KEY);
   }

   @Override
   public void onTerminate() {
       if (A4S.isInA4SProcess(this)) {
           return;
       }
       super.onTerminate();
   }

   @Override
   public void onConfigurationChanged(Configuration newConfig) {
       if (A4S.isInA4SProcess(this)) {
           return;
       }
       super.onConfigurationChanged(newConfig);
   }

   @Override
   public void onLowMemory() {
       if (A4S.isInA4SProcess(this)) {
           return;
       }
       super.onLowMemory();
   }
}

2)set user properties
final Dimelo dimelo = Dimelo.getInstance();
dimelo.setUserIdentifier(identifier);
dimelo.setUserName(name);
dimelo.setAuthenticationInfo(authInfo);

3)set jwt
final Dimelo dimelo = Dimelo.getInstance();
dimelo.setJwt(model.data.jwt);

4)set unread count listeners
final Dimelo dimelo = Dimelo.getInstance();
dimelo.fetchUnreadCount(new Dimelo.UnreadCountCallback() {
   @Override
   public void onSuccess(final int i) {
       Log.d("debug", "onSuccess: " + i);
   }

   @Override
   public void onError(final DimeloConnection.DimeloError dimeloError) {
       Log.d("debug", "onError: " + dimeloError.error);
   }
});
dimelo.setUnreadCountChangedListener(i -> Log.d("debug", "Unread count changed: " + i));
Log.d("debug", "Unread count: " + dimelo.getUnreadCount());


Here is intent service to handle notifications
public class GCMIntentService extends IntentService {

   public GCMIntentService() {
       super(GCMIntentService.class.getSimpleName());
   }

   @Override
   protected void onHandleIntent(final Intent intent) {
       final Bundle extras = intent.getExtras();
       final GoogleCloudMessaging gcm = GoogleCloudMessaging.getInstance(this);
       final String messageType = gcm.getMessageType(intent);
       if (!extras.isEmpty()) {
           if (GoogleCloudMessaging.MESSAGE_TYPE_SEND_ERROR.equals(messageType)
                   || GoogleCloudMessaging.MESSAGE_TYPE_DELETED.equals(messageType)) {
               return;
           }
           if (GoogleCloudMessaging.MESSAGE_TYPE_MESSAGE.equals(messageType)) {
               new Handler(Looper.getMainLooper()).post(() -> Dimelo.consumeReceivedRemoteNotification(this, extras, new DimeloNotificationDisplayer()));
           }
       }
   }
}
In DimeloNotificationDisplayer I have overridden the createPendingIntent method.

**Comment by waelba** [comment]
for `dimelo.setJwt(model.data.jwt);` your jwt is expired or invalid can you recheck it.
Can you send me the log content ?
BTW when you remove `dimelo.setJwt(model.data.jwt);` and you replace `Dimelo.getInstance().setApiKey(BuildConfig.DIMELO_API_KEY);` with `Dimelo.getInstance().setApiSecret(secret);
` it works ?

**Comment by waelba** [comment]
Did you manage to fix this issue ?
