### ISSUE TITLE
Push Notifications Issue

### ISSUE THREAD

**Issue by asellam** [dimelo/Dimelo-Android#35]
Hi Dimelo Team

We have an issue concerning push notifications functionality, we followed the steps described briefly here but we were unable to receive notifications.

1. we couldn't understand the meaning of SenderID in the first step (GoogleCloudMessaging.register(SenderID))

2. are we supposed to set SenderID=GCM_API_KEY from BuildConfig.java ??

3. GCM_API_KEY: is it supposed to be set to the default GOOGLE CLOUD MESSAGING API KEY ?? or does it only work by creating our own GCM account??
![image](https://user-images.githubusercontent.com/35767982/35338121-5181c974-011d-11e8-9b1b-830abf51d638.png)

Thanks in advance

**Comment by DrissTM** [comment]
Hi !

SenderID and the GCM_API_KEY are two different things that you can find in your Firebase/GCM account interface.

You need to create your own GCM account and use its credentials to handle notification in your application.

If you have any other questions don't hesitate to ask them here ;)

**Comment by asellam** [comment]
Hi again.

Thanks a lot for answering, once i try this i will be back with feedback.

Have a nice day

**Comment by asellam** [comment]
Hi Dimelo Team.

In the google cloud Platform i have three keys corresponding to my project:
1. Android Key
2. Server Key
3. Browser Key

Which one to use? and i still don't get the senderID thing
Help me please

Thanks in advance

**Comment by asellam** [comment]
Hi Again

It works finally, thanks a lot for answering Driss

**Comment by DrissTM** [comment]
Hi !

Good to hear ! If you need more help on this matter don't hesitate to contact us here ;)
