### ISSUE TITLE
Where to enable CameraAttachement and others

### ISSUE THREAD

**Issue by karimkod** [dimelo/Dimelo-Android#36]
Hello, So I've been looking into the docs, and I didn't found any method to enable CamearAttachement. The only one I found is to disbale or to check if enabled. 

Thank you.

**Comment by waelba** [comment]
Hi @karimkod, 

For camera activation just add the permission `<uses-permission adroid:name="android.permission.CAMERA" />`to your androidManifest

**Comment by waelba** [comment]
@karimkod Did you manage to fix this issue ?
