### ISSUE TITLE
After migrating to FCM we don't receive notifications

### ISSUE THREAD

**Issue by karimkod** [dimelo/Dimelo-Android#40]
After I migrated to FCM, I'm not receiving notifications and new messagees are not displayed on the chat fragment until I refresh it.
When I test to push a notification from Firebase console to the app it worked. but messages from dimelo platform are not.

**Comment by waelba** [comment]
Hi @karimkod ,

Did you download the google-services.jsonconsole from firebase and insert it into the `app` directory. Also, can you test if you received the device token when you use MyFirebaseMessagingService.java ?

**Comment by karimkod** [comment]
Yes, I've been using Firebase even before migrating so I have the google-services.json file in my project and I also receive the token (onNewToken is fired). As I mentioned the push from firebase to the app works perfectly but not from dimelo platform.

**Comment by waelba** [comment]
Have you configured the FCM server key on Dimelo Digital source? Can you also reinstall the app before testing the push notification ?

**Comment by karimkod** [comment]
What should I exactly configure on the dimelo digital source?

**Comment by waelba** [comment]
Put the FCM server key on the API Google Cloud Messaging key

![capture d ecran 2018-11-12 a 14 15 58 copie](https://user-images.githubusercontent.com/6080628/48349975-0d6c2f00-e686-11e8-8775-774838000fd1.png)


![capture d ecran 2018-11-12 a 14 14 01](https://user-images.githubusercontent.com/6080628/48350058-4d331680-e686-11e8-946a-9dc959628f04.png)

**Comment by karimkod** [comment]
Yes, I did that but still the same problem !

**Comment by waelba** [comment]
Can you send us the dimelo Application id and the dimelo domain name through a private channel?

**Comment by karimkod** [comment]
Okay, sure.

**Comment by waelba** [comment]
![capture d ecran 2018-11-12 a 14 40 19 copie](https://user-images.githubusercontent.com/6080628/48351030-3f32c500-e689-11e8-8db6-126b2fcf24ed.png)

**Comment by karimkod** [comment]
Can I have an email or something?

**Comment by waelbenabdallah** [comment]
Yes, wael.ben-abdallah@dimelo.com

**Comment by karimkod** [comment]
Sent.

**Comment by waelba** [comment]
Hello @karimkod ,

Can you give me a snippet of the code you're running for FCM registration ?

**Comment by karimkod** [comment]
Hi @waelbenabdallah, 

Thanks for you support, I think I fixed the issue it was due effectively to the FCM registration: 
When I was receiving the newToken I was verifying if Dimelo is instantiated but at that time it wasn't. so the deviceToken wasn't set. To fix that I saved the token on SharedPreference and get it from there when setting up Dimelo.

**Comment by waelba** [comment]
Hi @karimkod, 

You can use this code when  setting up Dimelo so you don't need to use the `SharedPreference`
  
```java
String refreshedToken = FirebaseInstanceId.getInstance().getToken();
        if (refreshedToken != null)
            dimelo.setDeviceToken(refreshedToken);
```

**Comment by karimkod** [comment]
Great, Thank you.
