### ISSUE TITLE
Release 1.6.9/1.7.0 issue

### ISSUE THREAD

**Issue by emiriel** [dimelo/Dimelo-Android#41]
Hi,

It seems like release 1.6.9 was erased by release 1.7.0 :
 - gradle doesn't find release 1.7.0
- when I set dimelo 1.6.9 on my project, i get errors regarding deprecated methods that should occur only with release 1.7.0

Regards,
Erwann

**Comment by waelba** [comment]
Hi @emiriel ,

Thanks for reporting the issue. it's fixed, can you test now with the two versions (1.7.0 and 1.6.9).

Best

**Comment by regislorient** [comment]
Hi,
It seems that release 1.6.9 still contains code of release 1.7.0 (by the way, the commit comment of the dimelosdk-1.6.9.aar file is "release 1.7.0"). As a consequence, the setApiSecret method is deprecated in release 1.6.9, although it should not be, according to CHANGELOG.md.
Regards.

**Comment by waelba** [comment]
Hi @regislorient ,

Thanks for reporting the issue. it's fixed, can you test now.

Best

**Comment by regislorient** [comment]
@waelbenabdallah 

I've just tested, and it correctly works now. Thanks.

**Comment by waelba** [comment]
Hi !

Good to hear ! If you need more help on this matter don't hesitate to contact us here ;)
