### ISSUE TITLE
Dimelo initialization crashes the app

### ISSUE THREAD

**Issue by karimkod** [dimelo/Dimelo-Android#42]
Version 1.6.9 
when initializing Dimelo with initWithApiSecret I'm having this exception: 

Caused by java.lang.IllegalArgumentException: Dimelo: Invalid domainName
       at com.dimelo.dimelosdk.main.Dimelo.setDomainName(Dimelo.java:850)
       at com.dimelo.dimelosdk.main.Dimelo.initWithApiSecret(Dimelo.java:487)
       at com.brenco.citylockerapp.view.MainActivity.setupDimelo(MainActivity.kt:242)
       at com.brenco.citylockerapp.view.MainActivity.onCreate(MainActivity.kt:117)
       at android.app.Activity.performCreate(Activity.java:6942)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by DrissTM** [comment]
Hi @karimkod according to the error message you're trying to setup the Dimelo instance with an invalid domain name.

What domain name did you pass to `initWithApiSecret` ? (the domain name is the second parameter)

**Comment by karimkod** [comment]
Hi @DrissTM it's the default mobilemessaging domain name => "mobilemessaging.engagement.dimelo.com"

**Comment by DrissTM** [comment]
_mobilemessaging.engagement.dimelo.com_ is the API hostname and cannot be changed.

As explained in the [documentation](https://github.com/dimelo/Dimelo-Android#migration-to-dimelo-170) `initWithApiSecret` now requires you to pass your domain name as parameter.
Your domain name can be found in your Dimelo url: **your-domain-name**.engagement.dimelo.com

Let me know if you have any other questions

**Comment by karimkod** [comment]
I'm still using the 1.6.9, is it deprecated now?

**Comment by karimkod** [comment]
@DrissTM When I did that now I can't send messages they keep loading and they are not sent, any idea why ?

**Comment by waelba** [comment]
Hello @karimkod,

Can you synchronize your app (app -> synchronize app)
then test, if the problem persist can you give me a snippet of the code for dimelo and gradle configuration

**Comment by waelba** [comment]
Hi @karimkod, 
Did you manage to resolve your issue ?

**Comment by karimkod** [comment]
Hi @waelbenabdallah Is the synchronization you mentioned the same as gradle sync or another type because I can't find it anyway!?

**Comment by waelba** [comment]
Hi @karimkod ,

Yes it's the same and please clean project and rebuild it because you always use to the old version of version 1.6.9 [this ticket](https://github.com/dimelo/Dimelo-Android/issues/41)

Let me know if you have any other questions

**Comment by karimkod** [comment]
It's not working. here are the snippets: 
` fun setupDimelo(context: Context, dimeloListener: Dimelo.DimeloListener): Dimelo {
        val secret = BuildConfig.DIMELO_SDK_SECRET //edit in gradle.properties
        Dimelo.setup(context)
        val dimelo = Dimelo.getInstance()


        dimelo.deviceToken = this.getSharedPreferences(
                getString(R.string.user_pref),
                Context.MODE_PRIVATE)
                ?.getString("FirebaseToken","")

        Log.d("MainActivity", dimelo.deviceToken)

        dimelo.initWithApiSecret(
                secret,
                "brenco.engagement.dimelo.com",
                dimeloListener
        )

        Injection.getUserRepository.getUserInfo(FirebaseAuth.getInstance().currentUser?.uid!!,
                object :UserInfoAccessor.ResponseCallback{
                    override fun onSuccess(info: SignUpInfo?) {
                        dimelo.userName = "Citylocker User | ${(info?.name)?:"Uknown"} ${(info?.lastName)?:""}"
                    }

                    override fun onFaillure() {
                            return
                    }

                })

        val authInfo = JSONObject()
        try {
            authInfo.put("Citylocker/Numéro_telephone", FirebaseAuth.getInstance().currentUser!!.phoneNumber)
        } catch (e: JSONException) {
            Log.d("MainActivity",e.toString())
        }

        dimelo.authenticationInfo = authInfo
        return dimelo
    }`

Gradle 

`
repositories {

    maven {
        url "https://raw.github.com/dimelo/Dimelo-Android/master"
    }
    maven { url 'https://maven.fabric.io/public' }


}

....
dependencies {
  
    implementation 'com.dimelo.dimelosdk:dimelosdk:1.7.0'
    //implementation 'com.google.android.gms:play-services-gcm:16.0.0'
    implementation "com.google.firebase:firebase-messaging:17.3.4"

    implementation 'com.google.gms:google-services:3.2.0'
    implementation 'com.squareup.retrofit2:retrofit:2.4.0'
    implementation 'com.google.firebase:firebase-database:16.0.4'
    implementation 'com.google.firebase:firebase-storage:16.0.4'

...

}

apply plugin: 'com.google.gms.google-services' `

**Comment by waelba** [comment]
As explained by @DrissTM here: https://github.com/dimelo/Dimelo-Android/issues/42#issuecomment-440680918, you only have to pass the first part (not `brenco.engagement.dimelo.com` but only `brenco`)

**Comment by karimkod** [comment]
Fixed, thanks.
