### ISSUE TITLE
With Android P on Pixel 2 and Pixel 3, Dimelo initialization fails and the app crahes

### ISSUE THREAD

**Issue by regislorient** [dimelo/Dimelo-Android#44]
Hello,
I use Dimelo Android SDK v1.6.9 in my app.
I recently tried to run the app on a Pixel 2 and a Pixel 3, with Android P and I realized that the app crashes at launch (and it does not with an Oreo device).

This is the stack trace:

    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
        at com.dimelo.volley.toolbox.HurlStack.performRequest(HurlStack.java:108)
        at com.dimelo.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:96)
        at com.dimelo.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)

It seems that the org.apache.http package (deprecated for years) finally disappeared on Android P.

I tried with SDK v1.7.0, and I got the same error.

Regards
Régis

**Comment by regislorient** [comment]
Here is a complement : I added \<uses-library android:name="org.apache.http.legacy" android:required="false" /\> as suggested in the Android documentation (https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library). This solved my problem.

If it has not been already done, I think this should be added in the Dimelo integration documentation.

Regards,
Régis

**Comment by waelba** [comment]
Hello @regislorient,

I will add this to documentation. Thanks.

**Comment by waelba** [comment]
Hi @regislorient  ,
It's fixed in `v1.7.1`
Thanks
