### ISSUE TITLE
Incident étrange

### ISSUE THREAD

**Issue by Alain44** [dimelo/Dimelo-Android#45]
Bonjour, ci-dessous la description d'un problème observé par deux personnes différentes.
1 - Mobile Huawei P9 Lite VNS-L31
Android 7.0
IMEI 860921032896389
HACK preprod
Depuis le mobile, j'ai envoyé une photo à Dimelo le 30/05/2018.
Le temps passe, plusieurs messages textes sont échangés entre Dimelo et moi.
Quand j'ouvre l'application, et que je me rends dans l'écran Dimelo : celui-ci est calé sur le message contenant la photo, plutôt que sur le message le plus récent que je viens de recevoir.
Pour voir le message le plus récent, je dois scroller.

2 - Et oui c’est un peu étrange ce comportement, je l’avais reproduit et je le reproduit encore en effet sur un Galaxy S9+ de cette façon : 
-       Connexion en Hackwifi avec le numéro 57101019 
-       Cliquer sur icône dimelo : Dimelo s’ouvre et se cale bien sur le dernier message envoyé
-       Cliquer sur la fléche Retour en haut à gauche
-       Et revenir dans Dimelo en cliquant sur l’icône : cette fois et toutes les fois suivantes, Dimelo s’ouvre et se cale sur la Photo, il faut scroller vers le bas pour arriver au dernier message.
  En résumé : 
-       Ouverture de Dimelo la 1ère fois : OK, j’arrive sur le dernier message
-       Ouverture de Dimelo la 2ème fois et les fois suivantes : J’arrive sur la photo et je dois scroller

**Comment by waelba** [comment]
Bonjour @Alain44,

Vous utilisez quelle version de notre SDK? 
En fragment ou en Activity ?
