### ISSUE TITLE
How to display the time when the notification was received

### ISSUE THREAD

**Issue by haha-lab** [dimelo/Dimelo-Android#47]
Hello, I want to ask how to display the notification time in the notification.

**Comment by waelba** [comment]
Hello @tulei94,
You can use the `d` value from the payload like this:

```java
private Long date = appData.getLong("d");
Log.e("date", DateFormat.getDateTimeInstance().format(new Date(date * 1000)));
```

**Comment by haha-lab** [comment]
Excuse me, android 7.0 push notifications show no time what to do?

**Comment by waelba** [comment]
Hello @tulei94, 

You can use  `NotificationCompat.Builder.setCustomContentView()` for that by implementing the `Dimelo.NotificationDisplayer` interface.

**Comment by haha-lab** [comment]
Hello, I want to ask, where should unreadCount be called? How should I call it?

**Comment by waelba** [comment]
Hello @tulei94, 

Please check our documentation: [The push notification section](https://github.com/dimelo/Dimelo-Android#push-notifications).

Thanks,

**Comment by haha-lab** [comment]
Hello, how should I test the Dimelo platform notifications?

**Comment by haha-lab** [comment]
Excuse me, what should I do if I want to add an attachment for the camera?

**Comment by DrissTM** [comment]
Hi @tulei94,

This repository's issues are dedicated to bug reports.

If you need assistance regarding the Dimelo Mobile SDK integration you will need to contact either our presales team if there's no ongoing project or our technical project managers who are in charge when it comes to technical support on this matter.

Can you tell what company you're working for so that I can redirect you to the right person ?

**Comment by haha-lab** [comment]
Hello, I can't receive the notification. In addition to the sample code on the Demo, what else do I need to configure?

**Comment by haha-lab** [comment]
Where is the dimelo digital source? How should I configure it to receive notification from dimelo?

**Comment by Bacdol** [comment]
Hi @tulei94,

Only Dimelo administrator can update the source configuration, please say us on which console do you work ? For the notification configuration we need to have the FCM token for Android and the APNS certficate for iOS (p12 file with passphrase or p8 file with team ID and certificate key).
