### ISSUE TITLE
Crash caused by a conflict with the Picasso lib

### ISSUE THREAD

**Issue by sebphil** [dimelo/Dimelo-Android#49]
Hi, we recently introduced the Picasso lib in version 2.71828 to our dependencies, and since then the Dimelo sdk crashes every time a user tries to use the file upload feature of Dimelo.

Here is the stack trace:
Fatal Exception: java.lang.NoSuchMethodError: No static method with(Landroid/content/Context;)Lcom/squareup/picasso/Picasso; in class Lcom/squareup/picasso/Picasso; or its super classes (declaration of 'com.squareup.picasso.Picasso' appears in base.apk)
       at com.dimelo.dimelosdk.utilities.GalleryCursorAdapter.onBindViewHolder(GalleryCursorAdapter.java:81)
       at com.dimelo.dimelosdk.utilities.GalleryCursorAdapter.onBindViewHolder(GalleryCursorAdapter.java:17)
       at com.dimelo.dimelosdk.utilities.CursorRecyclerViewAdapter.onBindViewHolder(CursorRecyclerViewAdapter.java:79)
...

The issue seems to be caused by a breaking change in Picasso, as seen on https://stackoverflow.com/questions/47844478/cannot-find-symbol-method-with-using-picasso-library-android.

Apparently the Dimelo sdk version 1.7.1 depends on Picasso version 2.4.0 which was released in 2014... We cannot downgrade the version of Picasso we use, because we need some of the new features. Could you please update this dependency ? Thanks in advance.

**Comment by waelba** [comment]
Hi @sebphil ,

This will be fixed in the next release.

I'll update this ticket to let you know as soon as we release the new version :)

**Comment by sebphil** [comment]
Hi @waelbenabdallah ! Any news on a release date for this fix? Firebase reports this is our top crash now, with more than 400 crashes over a month, so it's kinda urgent... Thank you for your help :)

**Comment by waelba** [comment]
Hi @sebphil,
We will make a release during the next week.

**Comment by sebphil** [comment]
ok thank you ;)

**Comment by waelba** [comment]
Hi @sebphil,
It's fixed in `v1.7.2`
Thanks
