### ISSUE TITLE
dimelo.setWelcomeMessage() could not receive a welcome message

### ISSUE THREAD

**Issue by haha-lab** [dimelo/Dimelo-Android#50]
dimelo.setWelcomeMessage() could not receive a welcome message

**Comment by jarthod** [comment]
Could you please be a bit more detailed about the issue you're having?

**Comment by haha-lab** [comment]
I called dimelo.setWelcomeMessage("jkdjtasjfjdkf") when I initialized; but when I first open dimelo's chat window, the chat window does not display the welcom message, my code is as follows:
public static Dimelo setupDimelo(Context context) {
        String secret = BuildConfig.DIMELO_SDK_SECRET;
        String domainName = BuildConfig.DIMELO_SDK_DOMAIN_NAME;
        Dimelo.setup(context);
        Dimelo dimelo = Dimelo.getInstance();
        dimelo.initWithApiSecret(secret, domainName, null);
        dimelo.setDebug(true);
        dimelo.setWelcomeMessage("jkdjtasjfjdkf");

        if (mRefreshedToken != null) {
            dimelo.setDeviceToken(mRefreshedToken);
        }
        return dimelo;
    }

**Comment by haha-lab** [comment]
I called dimelo.setWelcomeMessage("jkdjtasjfjdkf") when I initialized; but when I first open dimelo's chat window, the chat window does not display the welcom message, my code is as follows:
`public static Dimelo setupDimelo(Context context) {
        String secret = BuildConfig.DIMELO_SDK_SECRET;
        String domainName = BuildConfig.DIMELO_SDK_DOMAIN_NAME;
        Dimelo.setup(context);
        Dimelo dimelo = Dimelo.getInstance();
        dimelo.initWithApiSecret(secret, domainName, null);
        dimelo.setDebug(true);
        dimelo.setWelcomeMessage("jkdjtasjfjdkf");

        if (mRefreshedToken != null) {
            dimelo.setDeviceToken(mRefreshedToken);
        }
        return dimelo;
    }`

**Comment by haha-lab** [comment]
public static Dimelo setupDimelo(Context context) {
        String secret = BuildConfig.DIMELO_SDK_SECRET;
        String domainName = BuildConfig.DIMELO_SDK_DOMAIN_NAME;
        Dimelo.setup(context);
        Dimelo dimelo = Dimelo.getInstance();
        dimelo.initWithApiSecret(secret, domainName, null);
        dimelo.setDebug(true);
        dimelo.setWelcomeMessage("jkdjtasjfjdkf");

        if (mRefreshedToken != null) {
            dimelo.setDeviceToken(mRefreshedToken);
        }
        return dimelo;
    }
I called dimelo.setWelcomeMessage("jkdjtasjfjdkf") when I initialized; but when I first open dimelo's chat window, the chat window does not display the welcom message, above is my code

**Comment by haha-lab** [comment]
I called dimelo.setWelcomeMessage("jkdjtasjfjdkf") when I initialized; but when I first open dimelo's chat window, the chat window does not display the welcom message, my code is as follows:
public static Dimelo setupDimelo(Context context) {
        String secret = BuildConfig.DIMELO_SDK_SECRET;
        String domainName = BuildConfig.DIMELO_SDK_DOMAIN_NAME;
        Dimelo.setup(context);
        Dimelo dimelo = Dimelo.getInstance();
        dimelo.initWithApiSecret(secret, domainName, null);
        dimelo.setDebug(true);
        dimelo.setWelcomeMessage("jkdjtasjfjdkf");

        if (mRefreshedToken != null) {
            dimelo.setDeviceToken(mRefreshedToken);
        }
        return dimelo;
}

**Comment by haha-lab** [comment]
I called dimelo.setWelcomeMessage("jkdjtasjfjdkf") when I initialized; but when I first open dimelo's chat window, the chat window does not display the welcom message, my code is as follows:

public static Dimelo setupDimelo(Context context) {
        String secret = BuildConfig.DIMELO_SDK_SECRET;
        String domainName = BuildConfig.DIMELO_SDK_DOMAIN_NAME;
        Dimelo.setup(context);
        Dimelo dimelo = Dimelo.getInstance();
        dimelo.initWithApiSecret(secret, domainName, null);
        dimelo.setDebug(true);
        dimelo.setWelcomeMessage("jkdjtasjfjdkf");
        return dimelo;
}

**Comment by DrissTM** [comment]
Hi @haha-lab,

Unfortunately this method is not used anymore, sorry for the inconvenience and thanks for reporting this, we're going to remove it from the SDK.

In the mean time if you need to setup welcome messages in your application you will need to set them up in your Engage Digital (previously known as **Dimelo Digital**) mobile source.

You'll be able to create a message per language in your mobile source.
:warning: Please note that the message displayed will be the one that correspond to your mobile device language preference.

**Comment by waelba** [comment]
Hi @tylerlong ,
It's fixed in `v1.9.0`
Thanks
