### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by mkeyyy** [dimelo/Dimelo-Android#54]
Hello, i tried to change the dimelo_toolbar_title by setting it into the res string files, both in arabic and english strings, it worked on the english string res file and not on the arabic one.

I suggest you add another string res file and set the dimelo_toolbar_title there, or you can set it programatically when the language change listener gets triggered and set it whatever the user's language.

Regards;

**Comment by waelba** [comment]
Hello @mkeyyy,

For the language to be applied, the application must be closed and restarted, we do not change the language through a listener.

Regards,
Wael

**Comment by mkeyyy** [comment]
Hello Wael,

Already tried it by restarting the app with the arabic language set, no luck.

Regards

**Comment by waelba** [comment]
For the arabic language, you have to create a **values-ar** folder under **res** folder then you put inside `<string name="dimelo_toolbar_title">العنوان</string>`

<img src="https://user-images.githubusercontent.com/6080628/95072902-e0a2e400-0703-11eb-8234-b5c4d8c9c282.png" width=320 /> 

<img src="https://user-images.githubusercontent.com/6080628/95073144-3c6d6d00-0704-11eb-9b2f-1e1b0dd8ef85.png" width=320 />

**Comment by mkeyyy** [comment]
So sorry man, but already tried it too.
![local](https://user-images.githubusercontent.com/39320073/95074037-87907b80-0716-11eb-9923-d07365ff5667.PNG)

**Comment by waelba** [comment]
I have already sent to you a chat capture and the string is correctly displayed, surely it's a bad configuration of your project, other arabic strings is correctly displayed (screenshot if possible)

**Comment by mkeyyy** [comment]
👍 

![Screenshot_20201005-144240](https://user-images.githubusercontent.com/39320073/95076761-0b4c6700-071b-11eb-872e-3143be745a5b.png)
![Screenshot_20201005-144229](https://user-images.githubusercontent.com/39320073/95076774-0f788480-071b-11eb-8409-609894e7f891.png)
![Screenshot_20201005-144203](https://user-images.githubusercontent.com/39320073/95076783-13a4a200-071b-11eb-8a96-52044a9b9d5c.png)

**Comment by Bacdol** [comment]
You can close this one, managed on support side with the customer.
