### ISSUE TITLE
Last release breaks build of previous versions

### ISSUE THREAD

**Issue by evilya** [dimelo/Dimelo-Android#55]
In release 2.0.2 artifact "com.dimelo:picasso:1.0.0" was removed from the repository, that breaks build of all previous versions, that rely on your Picasso artifact. 

When I try to build my application with
`./gradlew build --refresh-dependencies`
I get the following error 

```
Could not resolve all artifacts for configuration ':app:commonDebugCompileClasspath'.
   Could not find com.dimelo:picasso:1.0.0.
     Required by:
         project :app > com.dimelo.dimelosdk:dimelosdk:2.0.1
```
Tested on versions 2.0.1 and 1.7.2. 

Hope it's not done on purpose to force an update to the latest version :) 
Thank you!

**Comment by DrissTM** [comment]
Hi @evilya !

It wasn't on purpose, I reverted the `picasso` artifact removal. You should be able to build without any issue now.
I'm closing this issue, don't hesitate to re-open if the issue still happens.

Thanks a lot for reporting this ! :+1:
