### ISSUE TITLE
Push Notification icon 

### ISSUE THREAD

**Issue by gbaccetta** [dimelo/Dimelo-Android#56]
Hello, 

I currently customize the push notification icon trough manifest for standard notification.
However, the sdk 2.0 use the app icon as a notification icon. Is there a way to change it without implementing Dimelo.NotificationDisplayer ?

thanks for your help,

Giovanni

**Comment by waelba** [comment]
Hi @gbaccetta ,

If you'd like to have the full control on the notification (appearance like icon, title... and behavior on click), you have to implement the `Dimelo.NotificationDisplayer` interface.

I'm closing this issue, feel free to create a new one if you have another question 🙂

Regards,
Wael
