### ISSUE TITLE
compileSdkVersion 31 build fail

### ISSUE THREAD

**Issue by haha825** [dimelo/Dimelo-Android#57]
Manifest merger failed : Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

**Comment by CedricBm** [comment]
Hello @tulei-hitron 

Please use v2.2.2 https://github.com/ringcentral/engage-digital-messaging-android/blob/master/CHANGELOG.md#dimelo-android-222-october-20th-2021 in which this issue is fixed

> Fix: Add android:exported="false" to Manifest to resolve the incompatibility with application targeting Android 12 and higher. RD-19794

Regards,
